version: "3.8"

services:

  application:

    build: .

    ports:
      - 80:8000

    depends_on:

      database:

        condition: service_healthy

    environment:

      - DATABASE_DB=${DATABASE_DB}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
      - ADMIN_USERNAME=${ADMIN_USERNAME}
      - ADMIN_EMAIL=${ADMIN_EMAIL}
      - ADMIN_PASSWORD=${ADMIN_PASSWORD}

    command: gunicorn --bind 0.0.0.0:8000 --workers ${WORKERS} CMS.wsgi

  database:

    image: postgres:alpine

    expose:
      - 5432

    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_DB}

    healthcheck:
      test: ["CMD", "pg_isready",'-U${DATABASE_USER}', '-d${DATABASE_DB}']
      interval: 10s
      timeout: 5s
      retries: 5

    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    
volumes:

  pgdata:
  
    driver: local