# Generated by Django 4.1.2 on 2022-11-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0002_remove_blogpost_id_blogpost_unique_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blogpost',
            old_name='unique_id',
            new_name='id',
        ),
    ]
