# Generated by Django 4.1.2 on 2022-11-02 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0009_remove_blogpost_id_blogpost_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='blogpost',
            name='slug',
            field=models.SlugField(null=True, unique=True, verbose_name='URL Slug'),
        ),
    ]
