# Generated by Django 4.1.2 on 2022-11-07 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0010_blogpost_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='uuid',
        ),
        migrations.AddField(
            model_name='blogpost',
            name='id',
            field=models.BigAutoField(auto_created=True, default=1, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
