# Generated by Django 4.1.2 on 2022-11-07 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0011_remove_blogpost_uuid_blogpost_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
