# Generated by Django 4.1.2 on 2022-11-07 12:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0013_alter_blogpost_body_alter_blogpost_description_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='slug',
        ),
    ]
