# Generated by Django 4.1.2 on 2022-11-07 12:57

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0014_remove_blogpost_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='body',
            field=models.TextField(default=1, max_length=5000),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='description',
            field=models.CharField(max_length=300),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(upload_to=post.models.upload_location),
        ),
        migrations.AlterField(
            model_name='blogpost',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
