# Generated by Django 4.1.2 on 2022-11-07 13:26

from django.db import migrations, models
import post.models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0015_alter_blogpost_body_alter_blogpost_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=post.models.upload_location),
        ),
    ]
