# Generated by Django 4.1.2 on 2022-11-07 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0016_alter_blogpost_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_deleted',
            field=models.DateTimeField(),
        ),
    ]
