# Generated by Django 4.1.2 on 2022-11-07 13:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0017_alter_blogpost_date_deleted'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blogpost',
            name='date_deleted',
            field=models.DateTimeField(null=True),
        ),
    ]
