# Generated by Django 4.1.2 on 2022-11-07 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0018_alter_blogpost_date_deleted'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blogpost',
            name='date_deleted',
        ),
    ]
