# Generated by Django 4.1.3 on 2023-06-28 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_code",
            field=models.CharField(default="283572", max_length=6, unique=True),
        ),
    ]
