# Generated by Django 4.1.3 on 2022-11-30 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="bio",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="account",
            name="display_picture",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
