# Generated by Django 4.1.3 on 2023-04-17 22:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0003_alter_user_verification_code"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="verification_code",
            field=models.CharField(default="035217", max_length=6, unique=True),
        ),
    ]
