# Generated by Django 4.1.3 on 2022-11-29 09:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0004_alter_account_user"),
    ]

    operations = [
        migrations.RenameField(
            model_name="account",
            old_name="name",
            new_name="account_name",
        ),
    ]
