# Generated by Django 4.1.3 on 2022-12-04 10:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0009_alter_user_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="account",
            name="display_picture",
            field=models.ImageField(
                default="blank-profile-picture.png", upload_to="profile_images"
            ),
        ),
    ]
