# Generated by Django 4.1.3 on 2022-12-19 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_account_display_picture'),
        ('accounts', '0010_alter_account_display_picture'),
    ]

    operations = [
    ]
