# Generated by Django 4.1.3 on 2023-01-03 10:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_merge_20221219_1042'),
        ('accounts', '0011_merge_20230102_2059'),
    ]

    operations = [
    ]
