# Generated by Django 4.1.3 on 2023-02-22 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="stori",
            name="published_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="stori",
            name="status",
            field=models.CharField(
                choices=[("drafted", "drafted"), ("published", "published")],
                default="drafted",
                max_length=20,
            ),
        ),
    ]
