# Generated by Django 4.1.3 on 2022-11-13 12:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='bio_data',
            new_name='bio',
        ),
    ]
