# Generated by Django 4.1.3 on 2023-02-07 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="stori",
            old_name="created_by",
            new_name="owner",
        ),
    ]
