# Generated by Django 4.1.3 on 2023-02-07 20:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0002_alter_category_options"),
        ("blog", "0002_rename_created_by_stori_owner"),
    ]

    operations = []
