# Generated by Django 4.1.3 on 2023-01-12 09:32

import ckeditor_uploader.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_stori_delete_blogpost'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stori',
            name='content',
            field=ckeditor_uploader.fields.RichTextUploadingField(),
        ),
    ]
