# Generated by Django 4.1.3 on 2022-11-15 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_remove_customuser_verifcation_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_photo',
            field=models.ImageField(blank=True, default='avatar.jpeg', null=True, upload_to='static/img/'),
        ),
    ]
