# Generated by Django 4.1.2 on 2022-10-28 14:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_alter_author_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='phonenumber',
            field=models.CharField(max_length=20),
        ),
    ]
