# Generated by Django 4.1.3 on 2023-03-23 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_comment_post_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stori",
            name="status",
            field=models.IntegerField(
                choices=[("Draft", "Draft"), ("Published", "Published")],
                default="Draft",
            ),
        ),
    ]
