# Generated by Django 4.1.3 on 2023-02-07 09:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_comment"),
    ]

    operations = [
        migrations.AlterField(
            model_name="comment",
            name="Post_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="blog.stori"
            ),
        ),
    ]
