# Generated by Django 4.1.2 on 2022-11-01 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_alter_author_date_created'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='unique_id',
            new_name='id',
        ),
    ]
