# Generated by Django 4.1.3 on 2023-03-27 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0004_alter_stori_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stori",
            name="status",
            field=models.CharField(
                choices=[("Draft", "Draft"), ("Published", "Published")],
                default="Draft",
                max_length=9,
            ),
        ),
    ]
