# Generated by Django 4.1.3 on 2023-02-26 08:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "__first__"),
        ("blog", "0004_alter_stori_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="stori",
            name="published_date",
        ),
        migrations.AlterField(
            model_name="stori",
            name="status",
            field=models.IntegerField(
                choices=[(0, "Draft"), (1, "Published")], default=0
            ),
        ),
        migrations.CreateModel(
            name="Reaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "reaction_type",
                    models.CharField(
                        choices=[("Like", "Like"), ("Dislike", "Dislike")],
                        max_length=100,
                    ),
                ),
                (
                    "comment",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.comment"
                    ),
                ),
                (
                    "post",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="blog.stori"
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="accounts.account",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
