# Generated by Django 4.1.3 on 2022-11-15 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_alter_profile_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='display_photo',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
